//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Services.Lesson_3.Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ILibrary", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ILibrary {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrary/IntroduceYourself", ReplyAction="http://tempuri.org/ILibrary/IntroduceYourselfResponse")]
        void IntroduceYourself(int idPerson, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrary/IntroduceYourself", ReplyAction="http://tempuri.org/ILibrary/IntroduceYourselfResponse")]
        System.Threading.Tasks.Task IntroduceYourselfAsync(int idPerson, string name);
        
        [System.ServiceModel.OperationContractAttribute(IsTerminating=true, Action="http://tempuri.org/ILibrary/GoAway", ReplyAction="http://tempuri.org/ILibrary/GoAwayResponse")]
        void GoAway();
        
        [System.ServiceModel.OperationContractAttribute(IsTerminating=true, Action="http://tempuri.org/ILibrary/GoAway", ReplyAction="http://tempuri.org/ILibrary/GoAwayResponse")]
        System.Threading.Tasks.Task GoAwayAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/ILibrary/ChooseNewBooks", ReplyAction="http://tempuri.org/ILibrary/ChooseNewBooksResponse")]
        void ChooseNewBooks(List<int> ids);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/ILibrary/ChooseNewBooks", ReplyAction="http://tempuri.org/ILibrary/ChooseNewBooksResponse")]
        System.Threading.Tasks.Task ChooseNewBooksAsync(int[] ids);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/ILibrary/HandOverBooks", ReplyAction="http://tempuri.org/ILibrary/HandOverBooksResponse")]
        void HandOverBooks(List<int> ids);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/ILibrary/HandOverBooks", ReplyAction="http://tempuri.org/ILibrary/HandOverBooksResponse")]
        System.Threading.Tasks.Task HandOverBooksAsync(int[] ids);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/ILibrary/ApplayChanges", ReplyAction="http://tempuri.org/ILibrary/ApplayChangesResponse")]
        string ApplayChanges();
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/ILibrary/ApplayChanges", ReplyAction="http://tempuri.org/ILibrary/ApplayChangesResponse")]
        System.Threading.Tasks.Task<string> ApplayChangesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILibraryChannel : Services.Lesson_3.Client.ServiceReference1.ILibrary, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibraryClient : System.ServiceModel.ClientBase<Services.Lesson_3.Client.ServiceReference1.ILibrary>, Services.Lesson_3.Client.ServiceReference1.ILibrary {
        
        public LibraryClient() {
        }
        
        public LibraryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LibraryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibraryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibraryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void IntroduceYourself(int idPerson, string name) {
            base.Channel.IntroduceYourself(idPerson, name);
        }
        
        public System.Threading.Tasks.Task IntroduceYourselfAsync(int idPerson, string name) {
            return base.Channel.IntroduceYourselfAsync(idPerson, name);
        }
        
        public void GoAway() {
            base.Channel.GoAway();
        }
        
        public System.Threading.Tasks.Task GoAwayAsync() {
            return base.Channel.GoAwayAsync();
        }
        
        public void ChooseNewBooks(List<int> ids) {
            base.Channel.ChooseNewBooks(ids);
        }
        
        public System.Threading.Tasks.Task ChooseNewBooksAsync(int[] ids) {
            return base.Channel.ChooseNewBooksAsync(ids);
        }
        
        public void HandOverBooks(List<int> ids) {
            base.Channel.HandOverBooks(ids);
        }
        
        public System.Threading.Tasks.Task HandOverBooksAsync(int[] ids) {
            return base.Channel.HandOverBooksAsync(ids);
        }
        
        public string ApplayChanges() {
            return base.Channel.ApplayChanges();
        }
        
        public System.Threading.Tasks.Task<string> ApplayChangesAsync() {
            return base.Channel.ApplayChangesAsync();
        }
    }
}
